FROM postgres:latest

ENV POSTGRES_DB=sqli_lab
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres123

RUN apt-get update && apt-get install -y curl

# Copy the initialization SQL file into the Docker container to initialize the database
COPY ./init.sql /docker-entrypoint-initdb.d/
COPY flag.txt /flag.txt
# Set proper permissions (Optional, if required for init.sql)
RUN chmod 755 /docker-entrypoint-initdb.d/init.sql
