# docker-compose.yml
version: '3'
services:
  web:
    build: .
    ports:
      - "84:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: electronics_store
      MYSQL_USER: store_user
      MYSQL_PASSWORD: store_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql