version: '3.9'
services:
  app:
    build:
      context: .
    container_name: php-app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8087:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli_lab
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_pass
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
